# Generated by Django 5.0.1 on 2024-01-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('command_text', models.CharField(max_length=255)),
                ('speaking_text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('action', models.CharField(choices=[('open_url', 'Open URL'), ('search', 'Search'), ('respond', 'Respond'), ('call', 'Call')], default='open_url', max_length=255)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sorting_order', '-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('assistant_name', models.CharField(max_length=255)),
                ('assistant_voice', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sorting_order', '-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
